---
collections:
  # Palo
  - name: paloaltonetworks.panos
    version: 2.21.4
  # pfSense
  - name: pfsensible.core
    version: 0.6.2
  # - name: vbotka.freebsd_pf
  # Cisco
  - name: cisco.fmcansible
    version: 1.0.2
  # Proxmox community.general.proxmox
  - name: community.general
    version: 6.5.0
  # VMware
  - name: community.vmware
    version: 4.1.0
